name: Run Python Script on Main Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies your script requires here

    - name: Run Python script
      run: python convert.py

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@users.noreply.github.com"

    - name: Commit and push JSON file
      run: |
        git add urls.json
        git commit -m "Update urls.json"
        git push